### PR TITLE
Shortcuts triggered by voice

### PR DESCRIPTION
**Pull request by adrianlzt**
I was thinking in a general way to create custom voice commands, but Google seems to have [blocked it for a while](https://developers.google.com/voice-actions/custom-actions).

I have integrated this workaround, using [search command](https://developer.android.com/guide/components/intents-common.html#SearchOnApp) to pass shortcuts names to the app.

Maybe related with #40

### CODE REVIEW

**Comment by adrianlzt** [comment]
I was trying to test if this works, because only published apps could recibe voice commands, so I create a new app on Google Play with the contents of this PR (changing the name, id, and some code not tested), but Google answered with:

> After review, Comandos, com.telefonica.dsmc.tools.http_shortcuts, has been suspended and removed from Google Play as a policy strike because it violates the impersonation policy. Your app is identical to an existing app on the Play Store.

I'm going to answer that this app is MIT licensed, so there is no problem copying it, but I just want to clarify that I just want to test this PR, and the app will never go public available.

Is this ok with you?

**Comment by adrianlzt** [comment]
Seems that app should be un "production" to be able to use Voice commands: https://plus.google.com/+AndroidDevelopers/posts/afSRdDQiy1N

I will comment when I receive a reply.

**Comment by Waboodoo** [comment]
Sounds like a cool idea. I was asked about voice commands before.

I am ok with you publishing your app, as long as you keep a reference back to my app in it of course.

I could just integrate your code changes in the next (or next after that) release of my app to test it out. That might be easier.

**Comment by adrianlzt** [comment]
Google has denied to pusblish the copy app, so, yes, will be easier to integrate changes.

The problem is how to test if Google Now sends the commands to the app. I was testing using this command: 
```
adb shell am start -a com.google.android.gms.actions.SEARCH_ACTION -e query foo
```

If I execute it against my android, it asks which app should be open, and works correctly with dropbox, for example.
Using voice seems to works corretly also. Something like "Search for cat in Dropbox".

**Comment by Waboodoo** [comment]
I was not able to directly merge your pull request due to the many changes I made in the latest version and the resulting conflicts. However, I included a basic experimental implementation into the latest release (1.12.0), which should now be live on the Play store. You should now be able to try if it works.

**Comment by adrianlzt** [comment]
Yeah, cool, it's working.

I have created a "testing" shortcut and say:
"search testing in H T T P shortcuts" and it executes the icon.

Related to this, I have find this:
https://developers.google.com/actions/
Is the new way of how to interact with the google assistant.
But seems more oriented to webservices than for apps.

Thanks for the work!

**Comment by Waboodoo** [comment]
Closing this as the feature is now already implemented (experimentally).

**Pull request closed without merging**
